language: ruby
rvm:
  - 2.2.5
gemfile:
  - Gemfile
deploy:
  provider: rubygems
  api_key:
    secure: frhK5TRyrplKjwEktkjx4nGyXBhELae7B/rfDTWUqLrwX4Gmx2XTf0j3VSwKphf2PclW2Phs1o029JFjivgjCB0gYpb4/lgPLxXAjYoUv7cbyZ1SdvIkhJsxilPgkPOr/t6XZ4OB1WU0yLJxDKNyJCh6fHJ47OlMfy7neGPtFKI=
  gemspec: pili.gemspec
  on:
    tags: true
